config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
    mount Sidekiq::Web, at: '/sidekiq'
  end
  root 'posts#index'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[index new create show]
  resources :posts, shallow: true do
    collection do
      get :search
    end
    resources :comments
  end
  resources :likes, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :activities, only: [] do
    patch :read, on: :member
  end

  resources :chatrooms, only: %i[index create show], shallow: true do
    resources :messages
  end

  namespace :mypage do
    resource :account, only: %i[edit update]
    resources :activities, only: %i[index]
    resource :notification_setting, only: %i[edit update]
  end
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id          :bigint           not null, primary key
#  body        :text(65535)      not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  chatroom_id :bigint
#  user_id     :bigint
#
# Indexes
#
#  index_messages_on_chatroom_id  (chatroom_id)
#  index_messages_on_user_id      (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (chatroom_id => chatrooms.id)
#  fk_rails_...  (user_id => users.id)
#
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user

  validates :body, presence: true, length: { maximum: 1000 }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_login, only: %i[create]
  def create
    @message = current_user.messages.build(message_params)
    if @message.save
      ActionCable.server.broadcast(
        "chatroom_#{@message.chatroom_id}",
        type: :create, html: (render_to_string partial: 'message', locals: { message: @message }, layout: false), message: @message.as_json
      )
      head :ok
    else
      head :bad_request
    end
  end

  def edit
    @message = current_user.messages.find(params[:id])
  end

  def update
    @message = current_user.messages.find(params[:id])
    if @message.update(message_update_params)
      ActionCable.server.broadcast(
        "chatroom_#{@message.chatroom_id}",
        type: :update, html: (render_to_string partial: 'message', locals: { message: @message }, layout: false), message: @message.as_json
      )
      head :ok
    else
      head :bad_request
    end
  end

  def destroy
    @message = current_user.messages.find(params[:id])
    @message.destroy!

    ActionCable.server.broadcast(
      "chatroom_#{@message.chatroom_id}",
      type: :delete, html: (render_to_string partial: 'message', locals: { message: @message }, layout: false), message: @message.as_json
    )
    head :ok
  end

  private

  def message_params
    params.require(:message).permit(:body).merge(chatroom_id: params[:chatroom_id])
  end

  def message_update_params
    params.require(:message).permit(:body)
  end
end

app/views/messages/_form.html.slim
= form_with model: [chatroom, message], remote: true do |f|
  = render 'shared/error_messages', object: message
  = f.label :body
  = f.text_field :body, class: 'form-control mb-3 input-message-body', required: true
  - if message.new_record?
    = f.submit '投稿', class: 'btn btn-primary btn-raised'
  - else
    = f.submit '更新', class: 'btn btn-primary btn-raised'

app/views/messages/_message.html.slim
li.media.mb-3.border-bottom.p-2 id="message-#{message.id}" data-sender-id="#{message.user.id}"
  div
    div
      = link_to message.user.username, user_path(message.user)
    = image_tag message.user.avatar_url, class: 'mr-3 rounded-circle', size: '50x50'

  .media-body
    = simple_format(message.body)
    div.text-right
      = message.decorate.created_at
    div.text-right.crud-area
      - if current_user&.own?(message)
        = link_to message_path(message), class: 'mr-3 delete-button', method: :delete, data: {confirm: '本当に削除しますか？'}, remote: true do
        = link_to edit_message_path(message), class: 'edit-button', remote: true do
          = icon 'far', 'edit', class: 'fa-sm'

app/views/messages/_modal_form.html.slim
.modal#message-edit-modal
  .modal-dialog
    .modal-content
      .modal-header
        h5.modal-title メッセージ編集
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  ×
      .modal-body
        = render 'form', chatroom: nil, message: @message

app/views/messages/edit.js.slim
| $("#modal-container").html("#{escape_javascript(render 'modal_form', message: @message)}");
| $("#message-edit-modal").modal('show');